# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import auto_phat_pb2 as auto__phat__pb2


class ControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setMorter = channel.unary_unary(
                '/Control/setMorter',
                request_serializer=auto__phat__pb2.Motor.SerializeToString,
                response_deserializer=auto__phat__pb2.Response.FromString,
                )
        self.setServo = channel.unary_unary(
                '/Control/setServo',
                request_serializer=auto__phat__pb2.Servo.SerializeToString,
                response_deserializer=auto__phat__pb2.Response.FromString,
                )


class ControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def setMorter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setServo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setMorter': grpc.unary_unary_rpc_method_handler(
                    servicer.setMorter,
                    request_deserializer=auto__phat__pb2.Motor.FromString,
                    response_serializer=auto__phat__pb2.Response.SerializeToString,
            ),
            'setServo': grpc.unary_unary_rpc_method_handler(
                    servicer.setServo,
                    request_deserializer=auto__phat__pb2.Servo.FromString,
                    response_serializer=auto__phat__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Control', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Control(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def setMorter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/setMorter',
            auto__phat__pb2.Motor.SerializeToString,
            auto__phat__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def setServo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Control/setServo',
            auto__phat__pb2.Servo.SerializeToString,
            auto__phat__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
